### ISSUE TITLE
0.11.9 - install fails/hangs

### ISSUE THREAD

**Issue by dasnervtdoch** [balderdashy/sails-hook-sockets#1]
I am getting the following issue when I try to install sails 0.11:

Users-MacBook-Pro:~ User$ npm install sails -g
-
> sails@0.11.0 preinstall /Users/User/.npm-packages/lib/node_modules/sails
> node ./lib/preinstall_npmcheck.js

> Sails.js Installation: Checking npm-version successful
> npm WARN deprecated grunt-lib-contrib@0.7.1: DEPRECATED. See readme: 
> https://github.com/gruntjs/grunt-lib-contrib
> npm WARN deprecated node-switchback@0.0.4: The 'node-switchback' NPM module is now simply 
> 'switchback'. See https://github.com/node-machine/switchback for latest docs.
> npm WARN deprecated node-switchback@0.0.2: The 'node-switchback' NPM module is now simply 
> 'switchback'. See https://github.com/node-machine/switchback for latest docs.
 
> ws@0.5.0 install /Users/User/.npm-packages/lib/node_modules/sails/node_modules/sails-hook-sockets/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

After that the process just hangs.

**Comment by tjwebb** [comment]
Some background discussion is here: https://gitter.im/balderdashy/sails?at=54e0d7da19f11886687041e5

**Comment by dasnervtdoch** [comment]
Actually `npm install ws` failed as well. I used the *.pkg installer for Mac OS X to install node.js `v 0.12` which installed node in `/usr/local`. I got rid of everything and downloaded the binaries and installed them locally to my user. I was able to run `npm install sails -g` successfully. Not a sails issue. Please close this issue and thanks for your help @tjwebb!

**Comment by tjwebb** [comment]
No problem! You can go ahead and close the issue, I can't do it on this repo.
