### ISSUE TITLE
v0.12.2 introduces possible bug, produces empty sails.sockets.subscribers() array

### ISSUE THREAD

**Issue by odnarb** [balderdashy/sails-hook-sockets#20]
Well, I've spent some time on this and I see #19 might be related to this.

I'll try to describe my setup as best as possible:
(This use case works with sails-hook-sockets@^0.11.28, but fails with sails-hook-sockets@^0.12.0)

Setup is: sails@0.11.4, but with sails-hook-sockets@^0.11.28

-On a controller have a socket client from a socket request join a room with sails.sockets.join(req.socket, "foo");
-Then check the subscribers in the room just joined in the same controller..on the next line..with
console.log(sails.sockets.subscribers("foo"));

The array is EMPTY on sails-hook-sockets@^0.12.0 and produces a state where I cannot communicate with subscribers...because there are seemingly none. However, the array is fine in 0.11.28.

I can't really look into this much more today as I'm kind of exhausted.

The one change between 0.11.28 and 0.12.2, splitting emit and whatnot.. I don't understand it, but maybe you can help me here.

Is this intended behavior?

**Comment by sgress454** [comment]
I would start by doing a clean install of Sails 0.11.4:

```
npm uninstall -g sails
npm cache clean
npm install sails
```

to make sure you've got all the right dependencies, especially the socket.io dependency of sails-hook-sockets.  `.subscribers()` hasn't changed between 0.11.28 and now, and the tests pass, so there _shouldn't_ be any difference.  If you still experience problems after a fresh install, can you post:

* Your node version
* Your NPM version
* Your operating system
and
* A link to an example repo, if possible?

Thanks!

**Comment by odnarb** [comment]
I did so, but for accuracy I'll it again.

Here's the sys info:

$ npm -v
3.3.12
$ node -v
v5.3.0
$ uname -a
Linux ubuntu 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:02 UTC 2015 i686 i686 i686 GNU/Linux
$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"
NAME="Ubuntu"
VERSION="14.04.3 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.3 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

**Comment by odnarb** [comment]
Let re-phrase what I meant by my last comment.

I did clean installs from 0.11.0 to 0.11.3, no problem. Then I did one last clean install of 0.11.4 and the feature broke.

Then, with 0.11.4 installed I downgraded sails-hook-sockets to the previous version stated in sails' change from the 0.11.3 tag to the 0.11.4 tag in the package.json: https://github.com/balderdashy/sails/compare/v0.11.3...v0.11.4
So I started with 0.11.4 installed, uninstalled the hook, reinstalled the hook with "^0.11.25", then stepped through to "^0.11.28" with no problems.

Then the step from "^0.11.28" to "^0.12.2" was the breaking change.

I'll see if I can produce a repo today with proof. If not I'll close the issue out.

**Comment by mikermcneil** [comment]
Thanks for all your help replicating, @odnarb.  Hopefully it's just some kind of dependency entanglement, but we'll get it sorted out one way or another.  Looking forward to your results.

**Comment by odnarb** [comment]
So, there was some nasty nasty issue with the dependencies in sails in the upgrade.

Did not want to track it down, closing this issue.

Thanks!

**Comment by marioblazev** [comment]
For what it's worth, the exact same thing happened to me and all real time functionality in my application stopped working.

I will follow in your tracks and downgrade sails-hook-sockets in the meantime, but a fix for this would be greatly appreciated as don't feel comfortable managing package versions.

**Comment by sgress454** [comment]
Update on this, FWIW--if you're using socket.io-redis, make sure you're on the latest version (1.0.0).  Previous versions do _not_ work with the newer versions of socket.io.
